name: Generate Daily M&A Digest

on:
  schedule:
    - cron: "0 13 * * *"  # Runs every day at 6am PST / 9am EST
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install feedparser rapidfuzz

      - name: Run scraper and generate HTML
        run: python generate_html.py

      - name: Test token permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" https://api.github.com/repos/${{ github.repository }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "🔄 Daily update: $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main


